export enum ENV_VARS {
  SECRET_KEY = 'SECRET_KEY',
  RESET_PASSWORD_SECRET_KEY = 'RESET_PASSWORD_SECRET_KEY',
  PORT = 'PORT',
  EMAIL_USER = 'EMAIL_USER',
  EMAIL_PASSWORD = 'EMAIL_PASSWORD',
  EMAIL_PORT = 'EMAIL_PORT',
  EMAIL_SERVICE = 'EMAIL_SERVICE',
  DATABASE_URL = 'DATABASE_URL',
}
